config/routes.rb
Irond::Application.routes.draw do
  root to: "home_pages#show"

  match "/login", to: "sessions#create", as: "login"
  match "/logout", to: "sessions#destroy", as: "logout"
  
  resources :products do
    collection do
      post :search
      get :search
      post :fill
    end
  end
  resource :subscriptions
  resource :home_page do
    get :administrate
    post :add_featured
    post :remove_featured
    collection do
      get :manage
    end
  end
  resource :sessions
  resource :user
end

app/controllers/home_pages_controller.rb
#encoding: utf-8
class HomePagesController < ApplicationController
  respond_to :js, :html
  before_filter :authenticate, except: [:show]
  
  def show
    @new_releases = Product.new_releases.shuffle
    @opportunities = Product.opportunities.shuffle
    @future_releases = Product.future_releases.shuffle
    @trailer_movie = Product.random_trailer
  end
  
  def administrate
    
  end
  
  def manage
    @products = Product.all
    @what = params[:what]
    @featured = case params[:what]
    when "new_releases"
      Product.new_releases
    when "opportunities"
      Product.opportunities
    when "coming_up"
      Product.future_releases
    end
  end
  
  def add_featured
    @product = Product.find_by_id(params[:product_id])
    @what = params[:what]
    case params[:what]
    when "new_releases"
      @product.update_attributes(new_release: true)
    when "opportunities"
      @product.update_attributes(opportunity: true)
    when "coming_up"
      @product.update_attributes(future_release: true)
    end
    
    respond_with @product, @what
  end
  
  def remove_featured
    @product = Product.find_by_id(params[:product_id])
    case params[:what]
    when "new_releases"
      @product.update_attributes(new_release: false)
    when "opportunities"
      @product.update_attributes(opportunity: false)
    when "coming_up"
      @product.update_attributes(future_release: false)
    end
    
    respond_with @product
  end
end

app/helpers/home_pages_helper.rb
#encoding: utf-8
module HomePagesHelper
  def trailer_helper(trailer_url)
    adjust_video return_video(trailer_url), "510", "305"
  end
  
  def what_heading_helper(what)
    case what
    when "opportunities"
      "Fırsatlar"
    when "new_releases"
      "Yeni Çıkanlar"
    when "coming_up"
      "Gelecek Vizyon"
    end
  end
  
  def featured_li_helper(product,what)
    html = ""
    html << ("<li id='product_#{product.id}'>")
    html << content_tag(:span, link_to(product.title, product_path(product.id)), class: "title")
    html << " - "
    html << link_to("Listeden kaldır", remove_featured_home_page_path(product_id: product.id,what: what), method: :post, remote: true, class: "underlined")
    html << "</li>"
    html.html_safe
  end
end

app/views/home_pages/add_featured.js.erb
$("#featured-items").append("<%= j featured_li_helper(@product, @what) %>");

app/views/home_pages/administrate.html.erb
<%= content_tag :div, id: "administration" do %>
	<%= content_tag :div, id: "add-new-movie" do %>
		<%= link_to "Yeni film ekle", new_product_path(type: "movie") %>
	<% end %>
	<%= content_tag :div, id: "add-new-accessories" do %>
		<%= link_to "Yeni aksesuar ekle", new_product_path(type: "accessory") %>
	<% end %>
	<%= content_tag :div, id: "add-new-game" do %>
		<%= link_to "Yeni oyun ekle", new_product_path(type: "game") %>
	<% end %>

	<%= content_tag :div, id: "manage-new-releases" do %>
		<%= link_to "Yeni çıkanlar", manage_home_page_path(what: "new_releases") %>
	<% end %>

	<%= content_tag :div, id: "manage-opportunities" do %>
		<%= link_to "Fırsatlar", manage_home_page_path(what: "opportunities") %>
	<% end %>

	<%= content_tag :div, id: "manage-future-releases" do %>
		<%= link_to "Yakında vizyona girecek filmler", manage_home_page_path(what: "coming_up") %>
	<% end %>

	<%= content_tag :div, id: "manage-subscriptions" do %>
		<%= link_to "Abonelikler", subscriptions_path %>
	<% end %>
	
	<%= content_tag :div, id: "manage-names" do %>
		<%= link_to "Slide İsimleri", edit_user_path %>
	<% end %>
<% end %>

app/views/home_pages/manage.html.erb
<%= form_tag add_featured_home_page_path, method: :post, remote: true ,id: "featured-form" do %>
	<%= content_tag :div, class: "field" do %>
		<%= label_tag "Ürün ismi:"%>
		<%= select_tag "product_id", options_for_select(@products.collect {|p| [p.title, p.id]})%>
		<%= hidden_field_tag :what, @what %>
		<%= submit_tag "Ekle"%>
	<% end %>
<% end %>

<%= content_tag :div, what_heading_helper(@what),id: "heading" %>
<%= content_tag :div, link_to("Yönetim sayfasına geri dön", administrate_home_page_path), id: "back-to-administration", class: "underlined" %>

<%= content_tag :ul, id: "featured-items" do %>
	<% if @featured.any? %>
		<% @featured.each do |f| %>
			<%= featured_li_helper(f, @what)%>
		<% end %>
	<% end %>
<% end %>

app/views/home_pages/remove_featured.js.erb
$("#product_<%= @product.id %>").remove();

app/views/home_pages/show.html.erb
<% if current_user %>
	<%= content_tag :div, id:"administration-links" do %>
		<%= content_tag :span, id: "adminstrate" do %>
			<%= link_to "Yönetim", administrate_home_page_path %>
		<% end %> | 
		
		<%= content_tag :span, id: "logout" do %>
			<%= link_to "Çıkış Yap", logout_path %>
		<% end %>
	<% end %>
<% end %>

<%= content_tag :div, id: "new-products" do %>
	<%= content_tag :div, id: "new-movie-trailer" do %>
		<% if @trailer_movie && movie_trailer = trailer_helper(@trailer_movie.trailer_url) %>
			<%= content_tag(:div, movie_trailer.html_safe, id: "trailer-wrapper") if @trailer_movie %>
		<% else %>
			<%= content_tag :div, "Fragman şu anda gösterilemiyor.", style: "height:185px;font-size: 20px;width:555px;text-align:center;padding-top:150px;position:relative;"%>
		<% end %>
		<%= content_tag :div, id: "info" do %>
			<%= content_tag :div, link_to(@trailer_movie.title, product_path(@trailer_movie.id))  if @trailer_movie %>
			<%= content_tag :div, class: "cast" do %>
				<%= content_tag :span, "Yönetmen: #{cast_helper(@trailer_movie.director, 2)}".html_safe if @trailer_movie %>
				<%= content_tag :span, "Oyuncular: #{cast_helper(@trailer_movie.actors, 3)}".html_safe if @trailer_movie %>
			<% end %>
		<% end %>
	<% end %>
	<%= content_tag :div, id: "new-products-slides" do %>
		<%= content_tag :div, id: "inner" do %>
			<%= content_tag :div, id: "limit" do %>
				<% if @new_releases %>
					<% @new_releases.each do |new_release| %>
						<%= content_tag :div, class: "single-slide" do %>
							<%= content_tag :div, link_to(image_tag(new_release.poster_url(:slide).to_s), product_path(new_release.id)), class: "poster" if new_release %>
							<%= content_tag :div, class: "new-release-info" do %>
								<% if new_release.product_type == "movie" %>
									<%= content_tag :div, class: "movie" do %>
										<%= content_tag :div, class: "text" do %>
											<%= content_tag :div, link_to(new_release.title, product_path(new_release.id)), class: "name" if new_release %>
											<%= content_tag :div, class: "cast" do %>
												<%= content_tag :div, "Yönetmen: #{cast_helper(new_release.director, 2)}".html_safe, class: "director" if new_release %>
												<%= content_tag :div, "Oyuncular: #{cast_helper(new_release.actors, 3)}".html_safe if new_release %>
											<% end %>
										<% end %>
									<% end %>
								<% else %>
									<%= content_tag :div, class: "game-or-accessory" do %>
										<%= content_tag :div, new_release.title, class: "name" if new_release %>
									<% end %>
								<% end %>
							<% end %>
						<% end %>
					<% end %>
					<%= content_tag :div, "", class: "cleaner"%>
				<% end %>
			<% end %>
		<% end %>
	<% end %>
	<%= content_tag :div, "", class: "cleaner"%>
	<%= content_tag :div, User.first.title_omega, id: "new-releases-title" %>
<% end %>
<%= content_tag :div, id: "future-releases-wrapper" do %>
	<%= content_tag :div, id: "future-releases" do %>
		<%= content_tag :div, User.first.title_alpha, id: "title-top"%>
		<%= content_tag :div, class: "limit-wrapper" do %>
			<%= content_tag :div, class: "limit", counter: "0" do %>
				<% if @future_releases %>
					<% @future_releases.each do |future_release| %>
						<%= content_tag :div, link_to(image_tag(future_release.poster_url(:thumb).to_s), product_path(future_release.id)), class: "slide" if future_release %>
					<% end %>
					<%= content_tag :div, "", class: "cleaner" %>
				<% end %>
			<% end %>
		<% end %>
		<%= content_tag :div, image_tag("home_page/left.png"), class: "left", style: "display:none;" %>
		<%= content_tag :div, image_tag("home_page/right.png"), class: "right" %>
	<% end %>
<% end %>

<%= content_tag :div, id: "discounted-movie-wrapper" do %>
	<%= content_tag :div, id: "discounted-movies" do %>
		<%= content_tag :div, class: "limit-wrapper" do %>
			<%= content_tag :div, class: "limit", counter: "0" do %>
				<% if @opportunities %>
					<% @opportunities.each do |opportunity| %>
						<%= content_tag :div, link_to(image_tag(opportunity.poster_url(:thumb).to_s), product_path(opportunity.id)), class: "slide" if opportunity %>
					<% end %>
					<%= content_tag :div, "", class: "cleaner" %>
				<% end %>
			<% end %>
		<% end %>
		<%= content_tag :div, image_tag("home_page/left.png"), class: "left", style: "display: none;" %>
		<%= content_tag :div, image_tag("home_page/right.png"), class: "right" %>
		<%= content_tag :div, User.first.title_beta, id: "title-bottom"%>
	<% end %>
<% end %>

<%= content_tag :div, id: "subscription-wrapper" do %>
	<%= content_tag :div, id: "subscription", method: :post do %>
		<%= content_tag :div, "HABERDAR OL", id: "subscribe" %>
		<%= form_tag subscriptions_path, method: :post do %>
			<%= text_field_tag :email, "Email" %>
			<%= submit_tag "" %>
		<% end %>
	<% end %>
	<%= content_tag :div, "", class: "cleaner"%>
<% end %>