config/routes.rb
Irond::Application.routes.draw do
  root to: "home_pages#show"

  match "/login", to: "sessions#create", as: "login"
  match "/logout", to: "sessions#destroy", as: "logout"
  
  resources :products do
    collection do
      post :search
      get :search
      post :fill
    end
  end
  resource :subscriptions
  resource :home_page do
    get :administrate
    post :add_featured
    post :remove_featured
    collection do
      get :manage
    end
  end
  resource :sessions
  resource :user
end

app/models/product.rb
# encoding: utf-8

require "net/http"
require "uri"
require "oembed"

class String
  def downcase_extended
    case self
    when "Ö"
      return "ö"
    when "Ş"
      return "ş"
    when "Ç"
      return "ç"
    when "İ"
      return "i"
    when "Ü"
      return "ü"
    else
      self.downcase
    end
  end
end

class Product < ActiveRecord::Base
  before_save :fill_initial
  before_update :fill_initial
  attr_accessible :title, :blue, :product_type, :initial, :poster, :summary, :normal_price, :discount_price, :year, :director, :duration, :language, :new_release, :actors, :opportunity, :future_release, :remote_poster_url, :trailer_url, :category_ids, :imdb_score
  
  has_and_belongs_to_many :categories
  
  default_scope -> { order("products.title ASC") }
  scope :by_type, ->(t) { where("products.product_type = ?", t)}
  scope :by_initial, ->(i) { where(initial: i)}
  scope :by_genre, ->(g) { joins(:categories).where("categories.title = ? ", g)}
  scope :new_releases, -> { where(new_release: true) }
  scope :opportunities, -> { where(opportunity: true) }
  scope :future_releases, -> { where(future_release: true) }
  scope :new_movie_with_trailer, -> { where(new_release: true).where(product_type: "movie").where("products.trailer_url != ''")}
  scope :blue, -> { where(blue: true) }
    
  define_index do
    indexes title
    indexes summary
    indexes actors
    indexes director
  end
  
  mount_uploader :poster, PosterUploader
  
  def self.random_trailer
    Product.new_movie_with_trailer.sample
  end
  
  def self.fetch_info(tmdb_url)
    info = Hash.new
    Tmdb.api_key = API_KEY[:tmdb]
    Tmdb.default_language = "tr"
    
    id = /\/movie\/(\w+)/.match(tmdb_url)
    if id.blank?
      return false
    else
      id = id[1].to_i
    end
    
    retries = 3
    movie = Hash.new
    begin
      movie[:tr] = TmdbMovie.find(id: id, language: "tr")
      movie[:en] = TmdbMovie.find(id: id, language: "en")
    rescue
      retries -= 1
      if retries > 0
        retry
      else
        return false
      end
    end
    
    if movie[:en].blank?
      return false
    end
    
    if movie[:tr].translated
      info[:summary] = movie[:tr].overview
    end
    info[:name] = movie[:en].name
    if (directors = movie[:en].cast.select {|cast| cast.department == "Directing"}) && !directors.blank?
      info[:directors] = directors.map(&:name) 
    end
    if (actors = movie[:en].cast.select {|cast| cast.department == "Actors"}) && !actors.blank?
      info[:actors] = actors.map(&:name).first(5) 
    end
    info[:duration] = movie[:en].runtime
    info[:year] = /(\d+)-/.match(movie[:en].released)[1].to_i
    info[:poster_url] = movie[:en].posters.select {|poster| (poster.width) > 225 && (poster.height > 330)}.first.url
    info[:trailer_url] = movie[:en].trailer if /youtube/.match(movie[:en].trailer)
    retries = 3
    begin
      OEmbed::Providers::Youtube.get(info[:trailer_url])
    rescue
      retries -= 1
      if retries > 0
        retry
      else
        info[:trailer_url] = nil
      end
    end
    if (genres = movie[:en].genres.map(&:name)) && !genres.blank?
      info[:categories] = Category.to_id(genres)
    end
    
    retries = 3
    begin
      imdb_scrape = Net::HTTP.get(URI.parse("http://www.imdb.com/title/#{movie[:en].imdb_id}/"))
    rescue
      retries -= 1
      if retries > 0
        retry
      else
        imdb_scrape = nil
      end
    end
    
    if imdb_scrape
      info[:imdb_score] = /<div class="star-box-giga-star">\n?(\d+{1,2}\.\d)/.match(imdb_scrape)[1]
    end
    
    info
  end
  
  protected
  
  def fill_initial
    self.initial = self.title[0]
  end
end

app/controllers/products_controller.rb
#encoding: utf-8
class ProductsController < ApplicationController
  before_filter :authenticate, except: [:index, :search, :show]
  respond_to :js, :html
  
  def index
    # type filter
    @products = Product.by_type(params[:type])
    @type = params[:type]
    
    # initial filter
    unless params[:initial].blank?
      @products = @products.by_initial(params[:initial]) 
      @initial = params[:initial]
    end
    
    # genre filter
    unless params[:genre].blank?
      if params[:genre] == "blue"
        @products = @products.blue
        @genre = "Blue Ray"
      else
        @products = @products.by_genre(params[:genre])
        @genre = Category.find_by_title(params[:genre])
      end
    end

    # pagination
    @products = @products.paginate(page: params[:page], per_page: 18)
  end
  
  def search
    @search = params[:search].strip if params[:search]
    @search = "" unless params[:search]
    @results = Product.search(params[:search], :page => params[:page], :per_page => 5)
    
    respond_with @results
  end
  
  def show
    @product = Product.find_by_id(params[:id])
  end
  
  def new
    @type = params[:type]
    @product = Product.new
  end
  
  def create
    @product = Product.new(params[:product])
    if @product.save
      redirect_to product_path(@product), notice: "Ürün başarıyla eklenmiştir."
    else
      render new_product_path
    end
  end
  
  def edit
    @type = params[:type]
    @product = Product.find_by_id(params[:id])
  end
  
  def update
    @product = Product.find_by_id(params[:id])
    
    if @product.update_attributes(params[:product])
      redirect_to product_path(@product), notice: "Ürün başarıyla güncellenmiştir."
    else
      render edit_product_path(@product)
    end
  end
  
  def destroy
    Product.find_by_id(params[:id]).destroy
    redirect_to root_path, notice: "Ürün başarıyla silinmiştir."
  end
  
  def fill
    @info = Product.fetch_info(params[:tmdb_url])
    
    respond_with @info
  end
end

app/helpers/products_helper.rb
# encoding: utf-8

class String
  def downcase_extended
    case self
    when "Ö"
      return "ö"
    when "Ş"
      return "ş"
    when "Ç"
      return "ç"
    when "İ"
      return "i"
    when "Ü"
      return "ü"
    else
      self.downcase
    end
  end
end

module ProductsHelper
  def trailer_helper(trailer_url)
    adjust_video return_video(trailer_url), "555", "335"
  end
  
  def genres_helper(product)
    genres = product.categories
    screen_name_collector = []
    genres.each do |genre|
      screen_name_collector << link_to(genre.screen_name, products_path(type: "movie", genre: genre.title, initial: "a"), class: "underlined")
    end
    screen_name_collector.join(", ").html_safe
  end
  
  def alphabet_helper(initial)
    alphabet_span = ""
    ALPHABET.each do |alp|
      alphabet_span << content_tag(:span, link_to(alp, products_path(initial: alp.downcase_extended, type: @type, genre: (@genre ? (@genre.is_a?(String) ? "blue" : @genre.title) : "")), style: "#{"color: orange;" if (alp.downcase == initial)}"), class: "letter")
    end
    alphabet_span.html_safe
  end
end

app/views/products/_accessory.html.erb
<%= content_tag :div, id: "movie" do %>
	<%= content_tag :div, id: "search-title-wrapper" do %>
		<%= content_tag :div, id: "search-title" do %>
			<%= content_tag :div, id: "outer" do %>
				<%= image_tag "products/ust_bar_alt_sol.png", id: "bg-bottom-left" %>
				<%= content_tag :span, id:"inner" do %>
					<%= image_tag "products/ust_bar_ust_sol.png", id: "bg-top-left" %>
					<%= content_tag :span, UnicodeUtils.upcase(product.title, :tr), id: "content" %>
					<%= image_tag "products/ust_bar_ust_sag.png", id: "bg-top-right" %>
					<%= content_tag :div, "", class: "cleaner" %>
				<% end %>
				<%= image_tag "products/ust_bar_alt_sag.png", id: "bg-bottom-left" %>
				<%= content_tag :div, "", class: "cleaner" %>
			<% end %>
		<% end %>
		<%= content_tag :div, "", class: "cleaner"%>
	<% end %>
	<%= content_tag :div, "", class: "cleaner"%>
	<% if current_user %>
		<%= content_tag :p, class: "edit-delete" do %>
			<%= link_to "Ürünü Düzenle", edit_product_path(id: product.id, type: product.product_type), class: "underlined" %> - <%= link_to "Ürünü Sil", product_path(product.id), method: :delete, confirm: "Silmek istediğinize emin misiniz?", class: "underlined"%>
		<% end %>
	<% end %>
	<%= content_tag :div, id: "accessory-poster", class: "visuals" do %>
		<%= content_tag :div, image_tag(product.poster_url(:movie_profile).to_s), id: "poster" %>
		<%= content_tag :div, "", class: "cleaner" %>
	<% end %>
	<%= content_tag :div, id: "info" do %>
		<%= image_tag "products/info_bg.png", id: "bg" %>
			<%= content_tag :div, id: "info-lines" do %>
			<%= content_tag :div, class: "info-line" do %>
				<%= content_tag :span, class: "info-pair" do %>
					<%= content_tag :span, "Fiyat:" ,class: "key" %>
					<%= content_tag :span, class: "value" do %>
						<% if product.discount_price.blank? %>
							<%= number_to_currency(product.normal_price, unit: "TL", precision: 2, format: "%n %u") %>
						<% else %>
							<%= content_tag :span, number_to_currency(product.normal_price, unit: "TL", precision: 2, format: "%n %u"), class: "overscore" %> 
							<%= number_to_currency(product.discount_price, unit: "TL", precision: 2, format: "%n %u") %>
						<% end %>
					<% end %>
				<% end %>
			<% end %>
			<%= content_tag :div, class: "info-line" do %>
				<%= content_tag :span, class: "info-pair" do %>
					<%= content_tag :span, "İşlev:", class: "key" %> <%= content_tag :span, product.summary, class: "value" %>
				<% end %>
			<% end%>
		<% end %>
	<% end %>
<% end %>

app/views/products/_game.html.erb
<%= content_tag :div, id: "movie" do %>
	<%= content_tag :div, id: "search-title-wrapper" do %>
		<%= content_tag :div, id: "search-title" do %>
			<%= content_tag :div, id: "outer" do %>
				<%= image_tag "products/ust_bar_alt_sol.png", id: "bg-bottom-left" %>
				<%= content_tag :span, id:"inner" do %>
					<%= image_tag "products/ust_bar_ust_sol.png", id: "bg-top-left" %>
					<%= content_tag :span, UnicodeUtils.upcase(product.title, :tr), id: "content" %>
					<%= image_tag "products/ust_bar_ust_sag.png", id: "bg-top-right" %>
					<%= content_tag :div, "", class: "cleaner" %>
				<% end %>
				<%= image_tag "products/ust_bar_alt_sag.png", id: "bg-bottom-left" %>
				<%= content_tag :div, "", class: "cleaner" %>
			<% end %>
		<% end %>
		<%= content_tag :div, "", class: "cleaner"%>
	<% end %>
	<%= content_tag :div, "", class: "cleaner"%>
	<% if current_user %>
		<%= content_tag :p, class: "edit-delete" do %>
			<%= link_to "Ürünü Düzenle", edit_product_path(id: product.id, type: product.product_type), class: "underlined" %> - <%= link_to "Ürünü Sil", product_path(product.id), method: :delete, confirm: "Silmek istediğinize emin misiniz?", class: "underlined"%>
		<% end %>
	<% end %>
	<%= content_tag :div, id: "game-poster" ,class: "visuals" do %>
		<%= content_tag :div, image_tag(product.poster_url(:movie_profile).to_s), id: "poster" %>
		<%= content_tag :div, "", class: "cleaner"%>
	<% end %>
	<%= content_tag :div, id: "info" do %>
		<%= image_tag "products/info_bg.png", id: "bg" %>
		<%= content_tag :div, id: "info-lines" do %>
			<%= content_tag :div, class: "info-line" do %>
				<%= content_tag :span, class: "info-pair" do %>
					<%= content_tag :span, "Fiyat:" ,class: "key" %>
					<%= content_tag :span, class: "value" do %>
						<% if product.discount_price.blank? %>
							<%= number_to_currency(product.normal_price, unit: "TL", precision: 2, format: "%n %u") %>
						<% else %>
							<%= content_tag :span, number_to_currency(product.normal_price, unit: "TL", precision: 2, format: "%n %u"), class: "overscore" %> 
							<%= number_to_currency(product.discount_price, unit: "TL", precision: 2, format: "%n %u") %>
						<% end %>
					<% end %>
				<% end %>
				<% unless product.year.blank? %>
					<%= content_tag :span, class: "info-pair" do %>
						<%= content_tag :span, "Sene:", class: "key" %> <%= content_tag :span, product.year.year, class: "value" %>
					<% end %>
				<% end %>
			<% end %>
			<%= content_tag :div, class: "info-line" do %>
				<%= content_tag :span, class: "info-pair" do %>
					<%= content_tag :span, "Konu:", class: "key" %> <%= content_tag :span, product.summary, class: "value" %>
				<% end %>
			<% end %>
		<% end %>
	<% end %>
<% end %>

app/views/products/_game_form.html.erb
<%= form_for @product, html: { multipart: true } do |f| %>
	<%= content_tag :div, class: "field" do %>
		<%= f.label :title, "İsim:" %><br />
		<%= f.text_field :title %>
	<% end %>
	
	<%= content_tag :div, class: "field" do %>
		<%= f.label :year, "Sene:" %><br />
		<%= f.date_select :year, discard_month: true, discard_day: true, include_blank: true, start_year: (Date.current.year + 2), end_year: 1900 %>
	<% end %>
	
	<%= content_tag :div, class: "field" do %>
		<%= f.label :poster, "Görsel:" %><br />
		<%= f.file_field :poster %>
	<% end %>
	
	<%= content_tag :div, class: "field" do %>
		<%= f.label :normal_price, "Normal Fiyat:" %><br />
		<%= f.text_field :normal_price %>
	<% end %>
	
	<%= content_tag :div, class: "field" do %>
		<%= f.label :discount_price, "İndirimli Fiyat:" %><br />
		<%= f.text_field :discount_price %>
	<% end %>
	
	<%= content_tag :div, class: "field" do %>
		<%= f.label :summary, "Konu:" %><br />
		<%= f.text_area :summary %>
	<% end %>
	
	<%= f.hidden_field :product_type, value: "game" %>
	
	<%= content_tag :div, class: "actions field" do %>
		<%= f.submit "Kaydet" %>
	<% end %>
<% end %>

app/views/products/_movie.html.erb
<%= content_tag :div, id: "movie" do %>
	<%= content_tag :div, id: "search-title-wrapper" do %>
		<%= content_tag :div, id: "search-title" do %>
			<%= content_tag :div, id: "outer" do %>
				<%= image_tag "products/ust_bar_alt_sol.png", id: "bg-bottom-left" %>
				<%= content_tag :span, id:"inner" do %>
					<%= image_tag "products/ust_bar_ust_sol.png", id: "bg-top-left" %>
					<%= content_tag :span, UnicodeUtils.upcase(product.title, :tr), id: "content" %>
					<%= image_tag "products/ust_bar_ust_sag.png", id: "bg-top-right" %>
					<%= content_tag :div, "", class: "cleaner" %>
				<% end %>
				<%= image_tag "products/ust_bar_alt_sag.png", id: "bg-bottom-left" %>
				<%= content_tag :div, "", class: "cleaner" %>
			<% end %>
		<% end %>
		<%= content_tag :div, "", class: "cleaner"%>
	<% end %>
	<%= content_tag :div, "", class: "cleaner"%>
	<% if current_user %>
		<%= content_tag :p, class: "edit-delete" do %>
			<%= link_to "Ürünü Düzenle", edit_product_path(id: product.id, type: product.product_type), class: "underlined" %> - <%= link_to "Ürünü Sil", product_path(product.id), method: :delete, confirm: "Silmek istediğinize emin misiniz?", class: "underlined"%>
		<% end %>
	<% end %>
	<%= content_tag :div, id: "movie-poster" ,class: "visuals" do %>
		<%= content_tag :div, image_tag(product.poster_url(:movie_profile).to_s), id: "poster" %>
		<% if video = trailer_helper(product.trailer_url) %>
			<%= content_tag :div, video.html_safe, id: "trailer" %>
		<% else %>
			<%= content_tag :div, "Fragman şu anda gösterilemiyor.", style: "height:185px;font-size: 20px;width:510px;text-align:center;padding-top:150px;position:relative;float:left"%>
		<% end %>
		<%= content_tag :div, "", class: "cleaner" %>
	<% end %>
	<%= content_tag :div, id: "info" do %>
		<%= image_tag "products/info_bg.png", id: "bg" %>
		<%= content_tag :div, id: "info-lines" do %>
			<%= content_tag :div, class: "info-line" do %>
				<%= content_tag :span, class: "info-pair" do %>
					<%= content_tag :span, "Fiyat:" ,class: "key" %>
					<%= content_tag :span, class: "value" do %>
						<% if product.discount_price.blank? %>
							<%= number_to_currency(product.normal_price, unit: "TL", precision: 2, format: "%n %u") %>
						<% else %>
							<%= content_tag :span, number_to_currency(product.normal_price, unit: "TL", precision: 2, format: "%n %u"), class: "overscore" %> 
							<%= number_to_currency(product.discount_price, unit: "TL", precision: 2, format: "%n %u") %>
						<% end %>
					<% end %>
				<% end %>
				<% unless product.imdb_score.blank? %>
					<%= content_tag :span, class: "info-pair" do %>
						<%= content_tag :span, "IMdb Puanı:", class: "key" %> <%= content_tag :span, product.imdb_score, class: "value" %>
					<% end %>
				<% end %>
				<% unless product.duration.blank? %>
					<%= content_tag :span, class: "info-pair" do %>
						<%= content_tag :span, "Süre:", class: "key" %> <%= content_tag :span, "#{product.duration} dk", class: "value" %>
					<% end %>
				<% end %>
				<% unless product.year.blank? %>
					<%= content_tag :span, class: "info-pair" do %>
						<%= content_tag :span, "Sene:", class: "key" %> <%= content_tag :span, product.year.year, class: "value" %>
					<% end %>
				<% end %>
				<%= content_tag :div, "", class: "cleaner"%>
			<% end %>
			<%= content_tag :div, class: "info-line" do %>
				<% unless product.categories.blank? %>
					<%= content_tag :span, class: "info-pair" do %>
						<%= content_tag :span, "Kategoriler:", class: "key" %> <%= content_tag :span, genres_helper(product), class: "value" %>
					<% end %>
				<% end %>
			<% end %>
			<%= content_tag :div, class: "info-line" do %>
				<%= content_tag :span, class: "info-pair" do %>
					<%= content_tag :span, "Konu:", class: "key" %> <%= content_tag :span, product.summary, class: "value", style: "text-justify: inter-word;" %>
				<% end %>
				<%= content_tag :div, "", class: "cleaner"%>
			<% end %>
			<% unless product.director.blank? %>
				<%= content_tag :div, class: "info-line" do %>
					<%= content_tag :span, class: "info-pair" do %>
						<%= content_tag :span, "Yönetmen:", class: "key" %> <%= content_tag :span, cast_helper(product.director), class: "value" %>
					<% end %>
					<%= content_tag :div, "", class: "cleaner"%>
				<% end %>
			<% end %>
			<% unless product.actors.blank? %>
				<%= content_tag :div, class: "info-line" do %>
					<%= content_tag :span, class: "info-pair" do %>
						<%= content_tag :span, "Oyuncular:", class: "key" %> <%= content_tag :span, cast_helper(product.actors), class: "value" %>
					<% end %>
					<%= content_tag :div, "", class: "cleaner"%>
				<% end %>
			<% end %>
			<% unless product.language.blank? %>
				<%= content_tag :div, class: "info-line" do %>
					<%= content_tag :span, class: "info-pair" do %>
						<%= content_tag :span, "Diller:", class: "key" %> <%= content_tag :span, product.language, class: "value" %>
					<% end %>
					<%= content_tag :div, "", class: "cleaner"%>
				<% end %>
			<% end %>
		<% end %>
	<% end %>
<% end %>

app/views/products/_movie_form.html.erb
<%= form_tag fill_products_path, method: :post, class: "fill-fields", remote: true do %>
	<%= content_tag :div, class: "field" do %>
		<%= label_tag :tmdb_url, "TMdb Link'i:" %>
		<%= url_field_tag :tmdb_url %>
		<%= submit_tag "Gönder" %>
	<% end %>
	
	<%= content_tag :div, "", class: "cleaner"%>
<% end %>

<%= form_for @product, html: { multipart: true }, class: "movie-form" do |f| %>
	<%= content_tag :div, class: "field" do %>
		<%= f.label :title, "İsim:" %><br />
		<%= f.text_field :title %>
	<% end %>
	
	<%= content_tag :div, class: "field" do %>
		<%= f.label :imdb_score, "IMdb Skoru:" %><br />
		<%= f.text_field :imdb_score %>
	<% end %>
	
	<%= content_tag :div, class: "field" do %>
		<%= f.label :year, "Sene:" %><br />
		<%= f.date_select :year, discard_month: true, discard_day: true, include_blank: true, start_year: (Date.current.year + 2), end_year: 1900 %>
	<% end %>
	
	<%= content_tag :div, class: "field" do %>
		<%= content_tag :div, "UYARI: Birden fazlaysa virgülle ayırınız. Örnek: \"Natalie Portman, Scarlett Johansson, Andrei Zvyagintsev, Fatih Akin\"", class: "note" %>
		<%= f.label :director, "Yönetmen:" %><br />
		<%= f.text_field :director %>
	<% end %>
	
	<%= content_tag :div, class: "field" do %>
		<%= content_tag :div, "Örnek: \"İngilizce, Türkçe, Almanca, Rusça\"", class: "note" %>
		<%= f.label :language, "Diller:" %><br />
		<%= f.text_field :language %>
	<% end %>
	
	<%= content_tag :div, class: "field" do %>
		<%= content_tag :div, "UYARI: Birden fazlaysa virgülle ayırınız. Örnek: \"Rachel Weisz, Adrien Broody, Mark Ruffalo, Rinko Kikuchi\"", class: "note" %>
		<%= f.label :actors, "Oyuncular:" %><br />
		<%= f.text_field :actors %>
	<% end %>
	
	<%= content_tag :div, class: "field" do %>
		<%= content_tag :div, "UYARI: İsterseniz bilgisayardan yükleyin isterseniz resmin web adresini verin. Fakat ikisini bir arada kullanmayın." %>
		<%= f.label :poster, "Görsel:" %><br />
		<%= f.file_field :poster %><br />
		URL: &nbsp&nbsp<%= f.text_field :remote_poster_url %>
	<% end %>
	
	<%= content_tag :div, class: "field" do %>
		<%= f.label :trailer_url, "Fragman Linki:" %><br />
		<%= f.text_field :trailer_url %>
	<% end %>
	
	
	<%= content_tag :div, class: "field" do %>
		<%= f.label :duration, "Süre:" %><br />
		<%= f.number_field :duration %>
	<% end %>
	
	<%= content_tag :div, class: "field" do %>
		<%= f.label :normal_price, "Normal Fiyat:" %><br />
		<%= f.text_field :normal_price %>
	<% end %>
	
	<%= content_tag :div, class: "field" do %>
		<%= f.label :discount_price, "İndirimli Fiyat:" %><br />
		<%= f.text_field :discount_price %>
	<% end %>
	
	<%= content_tag :div, class: "field" do %>
		<%= f.label :summary, "Konu:" %><br />
		<%= f.text_area :summary %>
	<% end %>
	
	<%= content_tag :div, class: "field" do %>
		<%= hidden_field_tag "product[category_ids][]", nil %>
		<% Category.all.in_groups_of(3,false) do |group| %>
			<% group.each do |category| %>
			    	<%= check_box_tag "product[category_ids][]", category.id, @product.category_ids.include?(category.id), id: dom_id(category) %>
			    	<%= label_tag dom_id(category), category.screen_name %>
			<% end %><br />
	  	<% end %>
	<% end %>
	
	<%= content_tag :div, class: "field" do %>
		<%= f.check_box :blue %><%= f.label :blue, "Blue Ray ise işaretleyin."%>
	<% end %>
	
	<%= f.hidden_field :product_type, value: @type %>
	
	<%= content_tag :div, class: "actions field" do %>
		<%= f.submit "Kaydet" %>
	<% end %>
	
	<% unless f.object.new_record? %>
		<%= content_tag :div, class: "email-image" do %>
			Email için 138x193 boyutundaki poster:<br /><br />
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= image_tag f.object.poster_url(:email).to_s %><br /><br />
			<%= content_tag :span, "URL:" %><input type="text" style="width:200px;" value="<%= "http://#{request.host}:#{request.port}" << f.object.poster_url(:email).to_s%>">
		<% end %>
	<% end %>
<% end %>

app/views/products/_products.html.erb
<% products.in_groups_of(6, false) do |group| %>
	<%= content_tag :div, class: "product-row" do %>
		<% group.each do |product| %>
			<%= content_tag :div, class: "product" do %>
				<%= content_tag :div, link_to(image_tag(product.poster_url(:thumb).to_s), product_path(product.id)), class: "visual" %>
				<%= content_tag :div, link_to(UnicodeUtils.upcase(product.title,:tr), product_path(product.id)), class: "title" %>
			<% end %>
		<% end %>
		<%= content_tag :div, "", class: "cleaner" %>
	<% end %>
<% end %>

app/views/products/_search_results.html.erb
<% results.each do |result| %>
	<% unless result == nil %>
		<%= content_tag :div, class: "result" do %>
			<%= content_tag :span, link_to(image_tag(result.poster_url(:smallest).to_s), product_path(result.id)), class: "visual" %>
			<%= content_tag :span, class: "name-summary" do %>
				<%= content_tag :div, class: "name-year" do %>
					<%= link_to result.title, product_path(result.id) %>
					<%= " (#{result.year.year})" unless result.year.blank?%>
				<% end %>
				<%= content_tag :div, truncate(result.summary, length: 200),class: "summary" %>
			<% end %>
			<%= content_tag :div, "", class: "cleaner" %>
		<% end %>
	<% end %>
<% end %>

app/views/products/edit.html.erb
<%= content_tag :div, "Ürünü düzenle", id: "heading" %>
<%= content_tag :div, link_to("Yönetim sayfasına geri dön", administrate_home_page_path), id: "back-to-administration", class: "underlined" %>

<%= render partial: "#{@type}_form" %>

app/views/products/index.js.erb
$('#products').append("<%= j render(partial: 'products', locals: {products: @products}) %>");
<% if @products.next_page %>
	$('#will-paginate-container').html('<%= will_paginate @products, page_links: false, container: false, next_label: content_tag(:div,"DEVAM") %>');
<% else %>
	$('#will-paginate-container').remove();
<% end %>

app/views/products/search.js.erb
$('#search-results').append("<%= j render(partial: 'search_results', locals: {results: @results}) %>");
<% if @results.next_page %>
	$('#will-paginate-container').html('<%= j will_paginate(@results, page_links: false, container: false, next_label: content_tag(:div,"DEVAM")) %>');
<% else %>
	$('#will-paginate-container').remove();
<% end %>

app/views/products/show.html.erb
<%= render partial: @product.product_type, locals: {product: @product}%>